language: node_js

branches:
  except:
    - /^v[0-9]/

node_js:
  - 8
  - 10

cache:
  yarn: true
  directories:
    - .eslintcache
    - node_modules

install:
  - yarn global add codecov
  - yarn

script:
  - yarn test:ci
  - yarn test:coverage && codecov
